### ISSUE TITLE
Para valorar en Time Tracking

### ISSUE THREAD

**Issue by alerchi** [ccalvarez/vuesax-time-tracking#29]
1. Permitir el Evento de la tecla Enter para guardar una tarea.
2. Permitir editar el nombre de una tarea para efectos de mostrar en el informe de labores

Eso sería por el momento jeje todo un éxito!

**Comment by alerchi** [comment]
Caro como son cosillas cosméticas agrego otra cosita que noté en este mismo Issue.

3. Dar foco al campo Nombre del Sistema, al dar clic en Nuevo Sistema en el mantenimiento, para no requerir dar clic para iniciar la digitación, o permitirlo al dar TAB.

Como parte del punto 1. que mencione antes, tomarlo en cuenta tambien en los mantenimientos.

Gracias,

**Comment by ccalvarez** [comment]
Resumen de issues resueltos:
 
- [ ] Permitir el Evento de la tecla Enter para guardar una tarea.
> También puedes presionar la tecla `INSERT `que equivale al click en botón `Nueva Tarea`
> También puedes presionar la tecla `ESC` para cerrar el dialog de propiedades de la tarea

- [ ] Permitir editar el nombre de una tarea para efectos de mostrar en el informe de labores
> Tengo pendiente permitir la edición de las tareas.  Lo atenderé en https://github.com/ccalvarez/vuesax-time-tracking/issues/11
- [ ] Dar foco al campo Nombre del Sistema, al dar clic en Nuevo Sistema en el mantenimiento, para no requerir dar clic para iniciar la digitación, o permitirlo al dar TAB
> El campo Nombre del Sistema recibirá el foco cada vez que se abra el dialog
- [ ] Como parte del punto 1. que mencione antes, tomarlo en cuenta tambien en los mantenimientos
> Tengo pendiente la edición de los sistemas.  Lo atenderé en https://github.com/ccalvarez/vuesax-time-tracking/issues/9

Gracias!

**Comment by alerchi** [comment]
Excelente, gracias Caro!
